server:
  port: ${SERVER_PORT:8090}
turbo:
  data:
    platform: mongodb
spring:
  application:
    name: template
config:
  limit-finished-task: ${CONFIG_LIMIT_FINISHED_TASK:5}
grpc:
  client:
    authorization-server:
      address: ${AUTHOR_GRPC_SERVER:static://localhost:9082}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT #TODO: Change to TLS on production after have cert
    tenant-server:
      address: ${TENANT_GRPC_SERVER:static://localhost:9081}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT #TODO: Change to TLS on production after have cert
logging:
  level:
    org:
      springframework:
        data: ${LOGGING_LEVEL:INFO}
    com:
      fpt:
        fis: ${LOGGING_LEVEL:INFO}