server:
  port: ${SERVER_PORT:8077}
turbo:
  security:
    ignore-path: ${AUTH_IGNORE_PATH:/licenses}
spring:
  application:
    name: license-management
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:admin}:${MONGODB_PASSWORD:admin}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DB_NAME:workpro-license-management}
logging:
  level:
    org:
      springframework:
        data: ${LOGGING_LEVEL:INFO}
    com:
      fpt:
        fis: ${LOGGING_LEVEL:INFO}

springbootwebfluxjjwt:
  password:
    encoder:
      secret: LicenseManagementService123!@#
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave65ByteLength
    expiration: 28800