server:
  port: ${SERVER_PORT:8077}
turbo:
  security:
    ignore-path: ${AUTH_IGNORE_PATH:/licenses}
spring:
  application:
    name: license-management
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:admin}:${MONGODB_PASSWORD:admin}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DB_NAME:workpro-license-management}
logging:
  level:
    org:
      springframework:
        data: ${LOGGING_LEVEL:INFO}
    com:
      fpt:
        fis: ${LOGGING_LEVEL:INFO}

job:
  constants:
    license-request-113:
      url: https://fisheyepubstore.fpt.com/bigquery/spro/
      cron: "0 0 0 20 * ? *"
